### PR TITLE
remove --quiet option from git format-patch

### PR DESCRIPTION
**Pull request by cehh**
With the --quiet option, the patch set generated by 'git format-patch; does not contain all the changes and some files may even be blank. 

Signed-off-by: Carlos Hernandez ceh@ti.com

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Hi Carlos,

That doesn't really sound like the '--quiet' option is causing that...

From: http://www.kernel.org/pub/software/scm/git/docs/git-format-patch.html
--quiet
Do not print the names of the generated files to standard output.

Regards,

**Comment by cehh** [comment]
On 01/15/2013 04:13 PM, Robert Nelson wrote:

> Hi Carlos,
> 
> That doesn't really sound like the '--quiet' option is causing that...
> 
> From: http://www.kernel.org/pub/software/scm/git/docs/git-format-patch.html
> --quiet
> Do not print the names of the generated files to standard output.
> 
> Regards,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/beagleboard/kernel/pull/20#issuecomment-12289535.
> 
> I know but that's what I observed.

Check the content of the export/_/_.patch after running patch.sh and you 
will see that there are some patch files, the even numbered ones in my 
case, with 0 bytes. After removing the --quiet option, the patches were 
properly generated.

Carlos

**Comment by RobertCNelson** [comment]
Hi Carlos,

Very strange... all the export/_/_.patch's look clean to me after running ./patch.sh...

Here's my system config:

voodoo@hades:/opt/github/kernel$ git branch 
- 3.8
  master

voodoo@hades:/opt/github/kernel$ echo $LANG
en_US.UTF-8

voodoo@hades:/opt/github/kernel$ git --version
git version 1.7.10.4

voodoo@hades:/opt/github/kernel$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.0 (wheezy)
Release:        7.0
Codename:       wheezy

Regards,

**Comment by cehh** [comment]
I'm using a different git version and I'm running ubuntu 10.04.
Here are my system details:

jenkins@jenkins1:/home/a0850405/jenkins/beagle/kernel$ git branch
- 3.8
  jenkins@jenkins1:/home/a0850405/jenkins/beagle/kernel$ echo $LANG
  en_US.UTF-8
  jenkins@jenkins1:/home/a0850405/jenkins/beagle/kernel$ git version
  git version 1.7.0.4
  jenkins@jenkins1:/home/a0850405/jenkins/beagle/kernel$ lsb_release -a
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 10.04.3 LTS
  Release:    10.04
  Codename:   lucid

**Comment by RobertCNelson** [comment]
Now that is weird....

-rw-r--r-- 1 voodoo voodoo  808 Jan 15 16:45 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pinctrl/0003-beaglebone-DT-set-default-triggers-for-LEDS.patch
-rw-r--r-- 1 voodoo voodoo    0 Jan 15 16:45 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pinctrl/0004-beaglebone-add-a-cpu-led-trigger.patch
-rw-r--r-- 1 voodoo voodoo 4.8K Jan 15 16:46 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0001-ARM-OMAP3-hwmod-Corrects-resource-data-for-PWM-devic.patch
-rw-r--r-- 1 voodoo voodoo    0 Jan 15 16:46 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0002-pwm_backlight-Add-device-tree-support-for-Low-Thresh.patch
-rw-r--r-- 1 voodoo voodoo 1.1K Jan 15 16:46 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0003-Control-module-EHRPWM-clk-enabling.patch
-rw-r--r-- 1 voodoo voodoo    0 Jan 15 16:46 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0004-pwm-pwm_test-Driver-support-for-PWM-module-testing.patch
-rw-r--r-- 1 voodoo voodoo  778 Jan 15 16:46 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0005-ARM-OMAP2-PWM-limit-am33xx_register_ehrpwm-to-soc_is.patch
-rw-r--r-- 1 voodoo voodoo    0 Jan 15 16:46 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0006-pwm-export-of_pwm_request.patch

It's like every other file for the whole patchset...

**Comment by RobertCNelson** [comment]
and with patch...
-rw-r--r-- 1 voodoo voodoo 4.9K Jan 15 16:56 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0001-ARM-OMAP3-hwmod-Corrects-resource-data-for-PWM-devic.patch
-rw-r--r-- 1 voodoo voodoo 2.6K Jan 15 16:56 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0002-pwm_backlight-Add-device-tree-support-for-Low-Thresh.patch
-rw-r--r-- 1 voodoo voodoo 1.2K Jan 15 16:56 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0003-Control-module-EHRPWM-clk-enabling.patch
-rw-r--r-- 1 voodoo voodoo  11K Jan 15 16:56 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0004-pwm-pwm_test-Driver-support-for-PWM-module-testing.patch
-rw-r--r-- 1 voodoo voodoo  876 Jan 15 16:56 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0005-ARM-OMAP2-PWM-limit-am33xx_register_ehrpwm-to-soc_is.patch
-rw-r--r-- 1 voodoo voodoo 2.3K Jan 15 16:56 /var/chroot/lucid-amd64/home/voodoo//kernel/export/pwm/0006-pwm-export-of_pwm_request.patch

Works as advertised on lucid, so i'll merge it. .;)

**Pull request merged**
