### PR TITLE
Create some simple kernel modules for examples

### PR DESCRIPTION
**Pull request by jadonk**
- One is just a simple hello world kernel module
- The other is something Jeff Lance wanted built

The current kernel build supports 1GHz, but does not allow register write accesses to the control module.  Heiu and Jeff need to access the bandgap_ctrl register to read internal temperature sensor data.

### CODE REVIEW

**Comment by koenkooi** [comment]
this is a hack, just write a hwmon driver for the temperature sensor 

Op 11 feb. 2013 om 20:33 heeft Jason Kridner notifications@github.com het volgende geschreven:

> One is just a simple hello world kernel module
> The other is something Jeff Lance wanted built
> The current kernel build supports 1GHz, but does not allow register write accesses to the control module. Heiu and Jeff need to access the bandgap_ctrl register to read internal temperature sensor data.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/jadonk/kernel 3.8
> Or view, comment on, or merge it at:
> 
>   https://github.com/beagleboard/kernel/pull/24
> 
> Commit Summary
> 
> Create some simple kernel modules for examples
> File Changes
> 
> A hacks/example-kernel-modules.patch (109)
> Patch Links:
> 
> https://github.com/beagleboard/kernel/pull/24.patch
> https://github.com/beagleboard/kernel/pull/24.diff

**Comment by jadonk** [comment]
I agree it is a hack. I'll provide the feedback to create a hwmon driver for the temperature sensor, but this is useful for hardware testing in the meantime. I don't have it applied, but I think it is useful to have around.

**Comment by koenkooi** [comment]
it's the ti version of /dev/exynos-mem, so a very bad idea.

Op 12 feb. 2013 om 09:47 heeft Jason Kridner notifications@github.com het volgende geschreven:

**Comment by jadonk** [comment]
I'll make a better pull request later to show an example kernel module.

**Pull request closed without merging**
