### PR TITLE
Fix aspect ratio issue of 720p in MT9M114 camera cape

### PR DESCRIPTION
**Pull request by meenumurali**
Fix the aspect ratio issue of 720p in MT9M114 camera cape.

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Thanks, pushed as part of: https://github.com/beagleboard/kernel/blob/9c7cb5b2c3d0c83ab27fe49895bf3a44180de87e/patches/capes/0021-Fix-aspect-ratio-issue-of-720p-in-MT9M114-camera-cap.patch

**Comment by RobertCNelson** [comment]
BTW... do you guys have a capture script & list of packages you need to have this work out of the box for end users?

**Comment by anithamol** [comment]
Thank you very much for  your fast reply.

  Our cape board SW run in standard V4L2 framework. So using any standard V4L2 application video can be captured and saved. We have tested the  same. The video can be played using any YUV 4:2:2  player.We will provide the V4L2 application if necessary.

**Comment by RobertCNelson** [comment]
This is merged, closing...

**Pull request closed without merging**
