### PR TITLE
Added configure step to README.md

### PR DESCRIPTION
**Pull request by jadonk**
Feel free to change the ARM= and CROSS_COMPILE=, but I think we need something that shows how to use the same configuration.

### CODE REVIEW

**Comment by koenkooi** [comment]
So this contains 2 changes :) For the README we should leave out the ARCH=arm stuff and only keep the cp.
For the hdmi stack: can you move it to the end of the PATCHSET variable? It has dependencies on the dma patches, so it should come after that to keep git bisect working.

**Comment by joelagnel** [comment]
I just pulled together several audio patches and resolved merge conflicts.
I will put at the end of PATCHSET and send you pull request tomorrow
morning. This is all me-time work. Good night.

**Comment by koenkooi** [comment]
I added the config bit to the README.md and Joel is doing a seperate request for the HDMI patches, so I'll close this request.

**Comment by jadonk** [comment]
@joelagnel ,

Did you look at the patches I created? I squashed the audio patches and resolved the conflicts already. What additional work are you doing? When are you going to send that pull request?

I'm trying to look at the instance creation now and how to integrate with capebus, since the board file is gone now.

**Comment by joelagnel** [comment]
I ./patch.sh'ed yesterday and there were patches related to audio dt and
davinci mcasp not there. I will double check and send patches shortly

Sent from my iPhone

On Oct 25, 2012, at 9:24 AM, Jason Kridner notifications@github.com wrote:

@joelagnel https://github.com/joelagnel ,

Did you look at the patches I created? I squashed the audio patches and
resolved the conflicts already. What additional work are you doing? When
are you going to send that pull request?

I'm trying to look at the instance creation now and how to integrate with
capebus, since the board file is gone now.

—
Reply to this email directly or view it on
GitHubhttps://github.com/beagleboard/kernel/pull/2#issuecomment-9779405.

**Pull request closed without merging**
